# Generated by Django 4.2.8 on 2023-12-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.CharField(default='', max_length=100),
        ),
    ]
